[package]
name = "Weather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
reqwest = {version = "0.12.4", features = ["blocking", "json"]}
serde_json = "1.0.117"
colored = "2.1.0"
regex = "1.10.4"